import { Geist, Cormorant_Garamond, Fleur_De_Leah } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const cormorantGaramond = Cormorant_Garamond({
  weight: ['400', '600', '700'],
  subsets: ['latin'],
  variable: '--font-cormorant-garamond',
});

const fleurDeLeah = Fleur_De_Leah({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-fleur-de-leah',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${cormorantGaramond.variable} ${fleurDeLeah.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
